### ISSUE TITLE
Artifact repository isn't correct

### ISSUE THREAD

**Issue by mateusz-lisik** [wallee-payment/android-till-sdk#1]
Hi. I wanted to attach this sdk to a project I'm working on, but it appears that [artifact repository](https://gitlab.com/api/v4/projects/21028526/packages/maven) is not valid. I assume that link may be correct but only for people in the gitlab organization.  

Since it is an OSS project anyway - I suggest to use Maven Central, or JCenter to host artifacts. For now, I built the code myself.

**Comment by thomashunziker** [comment]
We are aware of the current setup. Once the project reaches the point which we consider as stable we move on to use another repository.
