### ISSUE TITLE
ApiClient#bind should throw exception if creating intent / binding service fails

### ISSUE THREAD

**Issue by mateusz-lisik** [wallee-payment/android-till-sdk#2]
Right now, the `bind` method won't fail if `com.wallee.android.ApiService` is missing or can't be initialized. This creates NullPointerExceptions caused by `android.os.Messenger` being null when trying to interact with API. 

Having such exception would enable us to do sanity check on startup to determine if the runtime environment has everything we need. 

I can make PR for you if you want.

**Comment by thomashunziker** [comment]
We are looking into it. As your test pointed out we have with this matter an issue. We are currently checking if we just provide a better error message or if we can handle it in asynchronous way and the API call would still work in that scenario.
