### ISSUE TITLE
bind service result

### ISSUE THREAD

**Issue by Jacksotnik** [wallee-payment/android-till-sdk#3]
Can you return service binding result or throw Exception if service not bound? Currently, even if service not bound everything looks like success

**Comment by theodorspringwallee** [comment]
Dear [Jacksotnik](https://github.com/Jacksotnik)

Thank you for your request.

Please can you provide us a code example, that I can forward to our developers a specific example?

Do you mean you are not receiving a specific response, when the connection to our wallee API does not work?

I appreciate your answers.

**Comment by Jacksotnik** [comment]
```
final ApiClient client = new ApiClient(responseHandler);
client.bind(this);
```

client.bind(this) returns nothing and also not throwing exception if binding is unsuccess. 
From my view, will helpful to know if something wrong and service not bound
